spring:
#  security:
#    user:
#      name: jagjot
#      password: ok123
  application:
    name: project
  datasource:
    url: jdbc:postgresql://localhost:5432/speerDB
    username: speer
    password: db123
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  sql:
    init:
      mode: always
      schema-locations: classpath:sql/schema.sql
      data-locations: classpath:sql/data.sql
#    defer-datasource-initialization: true
#    generate-ddl: true

project:
  secret: qfG5QWBiPIQMFi1vBACK5ljqa5hJVWV1lXqfeV2cnJBSHjMkngNC/maSTQOUGhxm
  secs-to-expire: 86400